[pytest]
pythonpath = src
filterwarnings =
    ignore:datetime\.datetime\.utcnow\(\) is deprecated:DeprecationWarning:pydantic
    ignore:websockets\.legacy is deprecated:DeprecationWarning:websockets
